"""Create database model

Revision ID: e6cc3f592e91
Revises: 
Create Date: 2023-06-03 22:46:04.075169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6cc3f592e91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('user_name', sa.String(), nullable=True))
    op.drop_column('user_profile', 'first_name')
    op.drop_column('user_profile', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('last_name', sa.VARCHAR(), nullable=True))
    op.add_column('user_profile', sa.Column('first_name', sa.VARCHAR(), nullable=True))
    op.drop_column('user_profile', 'user_name')
    # ### end Alembic commands ###
